version: "3.8"

services:
  db:
    build:
      context: ./Server
      dockerfile: ./docker/Database/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=MysecretPassword123
    networks:
      - default
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  server:
    build: 
      context: ./Server
      dockerfile: ./docker/Dockerfile
    environment:
      - MSSQL_HOST=db
      - MSSQL_SA_PASSWORD=MysecretPassword123
    ports: 
      - "90:90"
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - default
  client:
    build:
      context: ./ngClient
      dockerfile: ./docker/Dockerfile
      args:
        HOST: http://localhost:90
    ports: 
      - "80:80"
    networks:
      - default
    depends_on:
      - server
networks:
  default:
    driver: bridge
volumes:
  mssql-data: