version: "3.8"

services:
  db:
    build:
      dockerfile: ./Server/docker/Dockerfile.databse
      context: ./Server
    environment:
      - MSSQL_SA_PASSWORD=MysecretPassword123
    networks:
      - default
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  server:
    build: 
      dockerfile: ./Server/docker/Dokerfile.server
      context: ./Server
    environment:
      - MSSQL_HOST=db
      - MSSQL_SA_PASSWORD=MysecretPassword123
    ports: 
      - "90:90"
    networks:
      - default
    depends_on:
      - db
  client:
    build:
      dockerfile: ./ngClient/docker/Dockerfile
      context: ./ngClient
      args:
        HOST: http://localhost:90
    ports: 
      - "80:80"
    networks:
      - default
    depends_on:
      - server
networks:
  default:
    driver: bridge
volumes:
  mssql-data: